# Trouble Shooting 20180723

## 创建 sriov 虚拟机失败

获取节点 overcloud-SriovPerformanceCompute-0 的地址
```
[stack@undercloud (stackrc) templates]$ nova list | grep -v OvsCompute
+--------------------------------------+-------------------------------------+--------+------------+-------------+------------------------+
| ID                                   | Name                                | Status | Task State | Power State | Networks               |
+--------------------------------------+-------------------------------------+--------+------------+-------------+------------------------+
| f6bb6a10-e563-4491-a34b-200f98c10246 | overcloud-Controller-0              | ACTIVE | -          | Running     | ctlplane=172.31.255.12 |
| 37509f43-0661-47a4-b1e5-c46d3e348f41 | overcloud-Controller-1              | ACTIVE | -          | Running     | ctlplane=172.31.255.4  |
| 8a151f7a-149c-4f26-b87d-90858286a21d | overcloud-Controller-2              | ACTIVE | -          | Running     | ctlplane=172.31.255.15 |
| 5f44dba5-d1a5-4311-bb35-54f499ac2323 | overcloud-SriovPerformanceCompute-0 | ACTIVE | -          | Running     | ctlplane=172.31.255.9  |
+--------------------------------------+-------------------------------------+--------+------------+-------------+------------------------+
```

查看接口情况，overcloud-SriovPerformanceCompute-0 上与本次部署有关的接口名称是 **eno49, eno50, ens3f0, ens3f1, ens2f0 和 ens2f1**
```
[stack@undercloud (stackrc) templates]$ ssh heat-admin@172.31.255.9 sudo ip link show | grep mtu
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT qlen 1
2: eno1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT qlen 1000
3: eno2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT qlen 1000
4: eno3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT qlen 1000
5: eno4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT qlen 1000
6: eno49: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq master ovs-system state UP mode DEFAULT qlen 1000
7: eno50: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq master ovs-system state UP mode DEFAULT qlen 1000
8: ens3f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP mode DEFAULT qlen 1000
9: ens3f1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP mode DEFAULT qlen 1000
10: ens2f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq master ovs-system state UP mode DEFAULT qlen 1000
11: ens2f1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq master ovs-system state UP mode DEFAULT qlen 1000
12: ovs-system: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT qlen 1000
13: br-tun: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT qlen 1000
14: br-int: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT qlen 1000
15: br-ex: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UNKNOWN mode DEFAULT qlen 1000
16: br-storage: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UNKNOWN mode DEFAULT qlen 1000
17: vlan323: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UNKNOWN mode DEFAULT qlen 1000
18: vlan324: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UNKNOWN mode DEFAULT qlen 1000
19: vlan325: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UNKNOWN mode DEFAULT qlen 1000
20: vlan326: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UNKNOWN mode DEFAULT qlen 1000
```

检查配置，发现配置与实际接口不一致，因此问题是由部署时模版与上述网卡不一致造成
```
[stack@undercloud (stackrc) templates]$ ssh heat-admin@172.31.255.9 sudo cat /etc/puppet/hieradata/sriovperformancecompute_extraconfig.yaml 
neutron::agents::ml2::ovs::extensions: qos, fdb
neutron::agents::ml2::sriov::physical_device_mappings: physnet1:enp216s0f1,physnet2:enp216s0f0
nova::compute::pci_passthrough: '[{"devname": "enp216s0f1", "physical_network": "physnet1"},{"devname": "enp216s0f0", "physical_network": "physnet2"}]'
tripleo::host::sriov::number_of_vfs: [
  "enp216s0f1:63",
  "enp216s0f0:63"
]
```

## 

计划向 availability zone 10 里的计算节点 overcloud-ovscompute-10.localdomain 上创建虚拟机，但是失败。检查日志发现控制节点未将实例调度到制定节点

```
2018-07-23 15:17:17.113 701703 ERROR nova.scheduler.utils [req-60ae4b81-a0a5-40db-8a12-7f30c0359aa9 18ea39ed65a74fba8e26072f398c9966 302e4a26ecc64ed2ab92c8c1c2610fbe - - -] [instance: 22442bb2-4632-47e0-b4f6-2d58b2010c7a] Error from last host: overcloud-ovscompute-4.localdomain (node overcloud-ovscompute-4.localdomain): [u'Traceback (most recent call last):\n', u'  File "/usr/lib/python2.7/site-packages/nova/compute/manager.py", line 1787, in _do_build_and_run_instance\n    filter_properties)\n', u'  File "/usr/lib/python2.7/site-packages/nova/compute/manager.py", line 1993, in _build_and_run_instance\n    instance_uuid=instance.uuid, reason=six.text_type(e))\n', u'RescheduledException: Build of instance 22442bb2-4632-47e0-b4f6-2d58b2010c7a was re-scheduled: Binding failed for port 77cc3bdf-fc90-4233-8330-732880b8a680, please check neutron logs for more information.\n']
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/server.py", line 199, in inner
    return func(*args, **kwargs)

  File "/usr/lib/python2.7/site-packages/nova/scheduler/manager.py", line 104, in select_destinations
    dests = self.driver.select_destinations(ctxt, spec_obj)

  File "/usr/lib/python2.7/site-packages/nova/scheduler/filter_scheduler.py", line 74, in select_destinations
    raise exception.NoValidHost(reason=reason)

NoValidHost: No valid host was found. There are not enough hosts available.

Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/server.py", line 199, in inner
    return func(*args, **kwargs)

  File "/usr/lib/python2.7/site-packages/nova/scheduler/manager.py", line 104, in select_destinations
    dests = self.driver.select_destinations(ctxt, spec_obj)

  File "/usr/lib/python2.7/site-packages/nova/scheduler/filter_scheduler.py", line 74, in select_destinations
    raise exception.NoValidHost(reason=reason)

NoValidHost: No valid host was found. There are not enough hosts available.
```

```
2018-07-23 15:16:17.915 983132 ERROR nova.scheduler.utils [req-60ae4b81-a0a5-40db-8a12-7f30c0359aa9 18ea39ed65a74fba8e26072f398c9966 302e4a26ecc64ed2ab92c8c1c
2610fbe - - -] [instance: 22442bb2-4632-47e0-b4f6-2d58b2010c7a] Error from last host: overcloud-ovscompute-11.localdomain (node overcloud-ovscompute-11.locald
omain): [u'Traceback (most recent call last):\n', u'  File "/usr/lib/python2.7/site-packages/nova/compute/manager.py", line 1787, in _do_build_and_run_instanc
e\n    filter_properties)\n', u'  File "/usr/lib/python2.7/site-packages/nova/compute/manager.py", line 1993, in _build_and_run_instance\n    instance_uuid=in
stance.uuid, reason=six.text_type(e))\n', u'RescheduledException: Build of instance 22442bb2-4632-47e0-b4f6-2d58b2010c7a was re-scheduled: Binding failed for 
port 77cc3bdf-fc90-4233-8330-732880b8a680, please check neutron logs for more information.\n']
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/server.py", line 199, in inner
    return func(*args, **kwargs)

  File "/usr/lib/python2.7/site-packages/nova/scheduler/manager.py", line 104, in select_destinations
    dests = self.driver.select_destinations(ctxt, spec_obj)

  File "/usr/lib/python2.7/site-packages/nova/scheduler/filter_scheduler.py", line 74, in select_destinations
    raise exception.NoValidHost(reason=reason)

NoValidHost: No valid host was found. There are not enough hosts available.
```

```
2018-07-23 15:15:23.731 288495 ERROR nova.scheduler.utils [req-60ae4b81-a0a5-40db-8a12-7f30c0359aa9 18ea39ed65a74fba8e26072f398c9966 302e4a26ecc64ed2ab92c8c1c
2610fbe - - -] [instance: 22442bb2-4632-47e0-b4f6-2d58b2010c7a] Error from last host: overcloud-ovscompute-12.localdomain (node overcloud-ovscompute-12.locald
omain): [u'Traceback (most recent call last):\n', u'  File "/usr/lib/python2.7/site-packages/nova/compute/manager.py", line 1787, in _do_build_and_run_instanc
e\n    filter_properties)\n', u'  File "/usr/lib/python2.7/site-packages/nova/compute/manager.py", line 1993, in _build_and_run_instance\n    instance_uuid=in
stance.uuid, reason=six.text_type(e))\n', u'RescheduledException: Build of instance 22442bb2-4632-47e0-b4f6-2d58b2010c7a was re-scheduled: Binding failed for 
port 77cc3bdf-fc90-4233-8330-732880b8a680, please check neutron logs for more information.\n']
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/server.py", line 199, in inner
    return func(*args, **kwargs)

  File "/usr/lib/python2.7/site-packages/nova/scheduler/manager.py", line 104, in select_destinations
    dests = self.driver.select_destinations(ctxt, spec_obj)

  File "/usr/lib/python2.7/site-packages/nova/scheduler/filter_scheduler.py", line 74, in select_destinations
    raise exception.NoValidHost(reason=reason)

NoValidHost: No valid host was found. There are not enough hosts available.
```

